### PR TITLE
[1.x] Fix trial ends at

### LINKED ISSUE #85: Unable to get trialEndsAt date without payment up front after trial expired
- Cashier Paddle Version: 1.2.2
- Laravel Version: 8.10.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 5.7.29

### Description:
After a trial has expired (without payment up front) the `trialEndsAt` method tries to get the trial_ends_at date from the subscription instead of the customer.

### Steps To Reproduce:
Create a user, then use the following to simulate a trial without payment up front that is expired:
```
$user->createAsCustomer([
    'trial_ends_at' => now()->subDays(10)
]);
```
When calling `$user->trialEndsAt()` the following exception is thrown: https://flareapp.io/share/J7oEp0Vm#F73

### PR DESCRIPTION
**Pull request by yoeriboven**
Fixes #85 

### Problem
Currently the `trialEndsAt` method checks if the user is on a generic trial. If it is then `trial_ends_at` on the User table will be returned. If it's not the trial of a subscription record will be returned.

This means that if a user used to be on a generic trial which is now expired, it will look for a (non-existent) subscription record instead of the `trial_ends_at` field and throw an exception.

### Solution
With this PR `trialEndsAt` will check if there is a subscription. If there is not a subscription it will return the date from the `trial_ends_at` field. If there is a subscription, it will return the subscription.

### CODE REVIEW

File: src/Concerns/ManagesSubscriptions.php [hunk 1]
```diff
@@ -84,7 +84,7 @@ public function onGenericTrial()
      */
     public function trialEndsAt($name = 'default')
     {
-        if ($this->onGenericTrial()) {
+        if (is_null($this->subscription($name))) {
```
Comment (GrahamCampbell) [inline src/Concerns/ManagesSubscriptions.php:87]: Should not double call this.

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]

**Review by driesvints — APPROVED** [review]
Lgtm. Thanks @yoeriboven.

**Comment by driesvints** [comment]
This actually also solves a problem with the `onGenericTrial` that checks if the trial date is in the future, which isn't needed. You just want the end date back, regardless of the trial having ended or not.

**Review by GrahamCampbell — APPROVED** [review]
