### PR TITLE
[2.x] Fixed trial ends at

### LINKED ISSUE #122: Fix trialEndsAt more closely represents onTrial
Should [this PR](https://github.com/laravel/cashier-stripe/pull/1129) on Cashier Stripe also be done on Cashier Paddle?

### PR DESCRIPTION
**Pull request by yoeriboven**
Closes #122 and is a replica of laravel/cashier-stripe#1129.

When on a generic trial but also having an active subscription, it will now return the ending date of the generic trial instead of the subscription.

### CODE REVIEW

File: src/Concerns/ManagesSubscriptions.php [hunk 1]
```diff
@@ -85,6 +85,10 @@ public function onGenericTrial()
      */
     public function trialEndsAt($name = 'default')
     {
+        if (func_num_args() === 0 && $this->onGenericTrial()) {
```
Comment (GrahamCampbell) [inline src/Concerns/ManagesSubscriptions.php:88]: >  `func_num_args() === 0`

That part seems wrong?

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]

File: src/Concerns/ManagesSubscriptions.php (hunk 1 above)
Comment (driesvints) [reply src/Concerns/ManagesSubscriptions.php:88]: No that's correct. See the cashier PR

**Review by driesvints — APPROVED** [review]
